////////////////////////
/// Made by Team AOF ///
////////////////////////


ServerEvents.tags('item', event => {

    const replicator = [
        'kibe:tank',
        'kibe:angel_ring',
        'ae2:quantum_entangled_singularity',
        'ae2:spatial_storage_cell_2',
        'ae2:spatial_storage_cell_16',
        'ae2:spatial_storage_cell_128',
        'ae2:sky_stone_tank',
        'ae2:portable_item_cell_1k',
        'ae2:portable_item_cell_4k',
        'ae2:portable_item_cell_16k',
        'ae2:portable_item_cell_64k',
        'ae2:portable_item_cell_256k',
        'ae2:portable_fluid_cell_1k',
        'ae2:portable_fluid_cell_4k',
        'ae2:portable_fluid_cell_16k',
        'ae2:portable_fluid_cell_64k',
        'ae2:portable_fluid_cell_256k',
        'ae2:item_storage_cell_1k',
        'ae2:item_storage_cell_4k',
        'ae2:item_storage_cell_16k',
        'ae2:item_storage_cell_64k',
        'ae2:item_storage_cell_256k',
        'ae2:fluid_storage_cell_1k',
        'ae2:fluid_storage_cell_4k',
        'ae2:fluid_storage_cell_16k',
        'ae2:fluid_storage_cell_64k',
        'ae2:fluid_storage_cell_256k',
        'botania:dice',
        'botania:infinite_fruit',
        'botania:king_key',
        'botania:flugel_eye',
        'botania:thor_ring',
        'botania:odin_ring',
        'botania:loki_ring',
        'botania:mana_tablet',
        'botania:mana_ring',
        'botania:mana_ring_greater',
        'minecraft:dragon_egg',
        'kibe:golden_lasso',
        'kibe:cursed_lasso',
        'kibe:diamond_lasso',
        'modern_industrialization:quantum_helmet',
        'modern_industrialization:quantum_chestplate',
        'modern_industrialization:quantum_leggings',
        'modern_industrialization:quantum_boots',
        'modern_industrialization:quantum_sword',
        'modern_industrialization:singularity',
        'artifacts:everlasting_beef',
        'artifacts:eternal_steak',
        'megacells:bulk_item_cell',
        'megacells:mega_energy_cell',
        'megacells:item_storage_cell_1m',
        'megacells:item_storage_cell_4m',
        'megacells:item_storage_cell_16m',
        'megacells:item_storage_cell_64m',
        'megacells:item_storage_cell_256m',
        'megacells:fluid_storage_cell_1m',
        'megacells:fluid_storage_cell_4m',
        'megacells:fluid_storage_cell_16m',
        'megacells:fluid_storage_cell_64m',
        'megacells:fluid_storage_cell_256m',
        'megacells:portable_item_cell_1m',
        'megacells:portable_item_cell_4m',
        'megacells:portable_item_cell_16m',
        'megacells:portable_item_cell_64m',
        'megacells:portable_item_cell_256m',
        'megacells:portable_fluid_cell_1m',
        'megacells:portable_fluid_cell_4m',
        'megacells:portable_fluid_cell_16m',
        'megacells:portable_fluid_cell_64m',
        'megacells:portable_fluid_cell_256m',
        'powah:battery_starter',
        'powah:battery_basic',
        'powah:battery_hardened',
        'powah:battery_blazing',
        'powah:battery_niotic',
        'powah:battery_spirited',
        'powah:battery_nitro',
        'appbot:mana_storage_cell_1k',
        'appbot:mana_storage_cell_4k',
        'appbot:mana_storage_cell_16k',
        'appbot:mana_storage_cell_64k',
        'appbot:mana_storage_cell_256k',
        'appbot:portable_mana_storage_cell_1k',
        'appbot:portable_mana_storage_cell_4k',
        'appbot:portable_mana_storage_cell_16k',
        'appbot:portable_mana_storage_cell_64k',
        'appbot:portable_mana_storage_cell_256k'

    ];

    replicator.forEach((item) => {
        event.add('modern_industrialization:replicator_blacklist', item)
    });

});
